# Generated by Django 4.0.3 on 2022-04-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=0, help_text='Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc. )', max_length=200),
            preserve_default=False,
        ),
    ]
